// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using housing_location_backend.Data;

#nullable disable

namespace housing_location_backend.Migrations
{
    [DbContext(typeof(WebAPIDbContext))]
    partial class WebAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("housing_location_backend.Models.HousingLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AvailableUnits")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Laundry")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Wifi")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("HousingLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableUnits = 4,
                            City = "Chicago",
                            Laundry = true,
                            Name = "Acme Fresh Start Housing",
                            Photo = "https://angular.dev/assets/images/tutorials/common/bernard-hermant-CLKGGwIBTaY-unsplash.jpg",
                            State = "IL",
                            Wifi = true
                        },
                        new
                        {
                            Id = 2,
                            AvailableUnits = 0,
                            City = "Santa Monica",
                            Laundry = true,
                            Name = "A113 Transitional Housing",
                            Photo = "https://angular.dev/assets/images/tutorials/common/brandon-griggs-wR11KBaB86U-unsplash.jpg",
                            State = "CA",
                            Wifi = false
                        },
                        new
                        {
                            Id = 3,
                            AvailableUnits = 1,
                            City = "Juneau",
                            Laundry = false,
                            Name = "Warm Beds Housing Support",
                            Photo = "https://angular.dev/assets/images/tutorials/common/i-do-nothing-but-love-lAyXdl1-Wmc-unsplash.jpg",
                            State = "AK",
                            Wifi = false
                        },
                        new
                        {
                            Id = 4,
                            AvailableUnits = 1,
                            City = "Chicago",
                            Laundry = false,
                            Name = "Homesteady Housing",
                            Photo = "https://angular.dev/assets/images/tutorials/common/ian-macdonald-W8z6aiwfi1E-unsplash.jpg",
                            State = "IL",
                            Wifi = true
                        },
                        new
                        {
                            Id = 5,
                            AvailableUnits = 1,
                            City = "Gary",
                            Laundry = false,
                            Name = "Happy Homes Group",
                            Photo = "https://angular.dev/assets/images/tutorials/common/krzysztof-hepner-978RAXoXnH4-unsplash.jpg",
                            State = "IN",
                            Wifi = true
                        },
                        new
                        {
                            Id = 6,
                            AvailableUnits = 2,
                            City = "Oakland",
                            Laundry = true,
                            Name = "Hopeful Apartment Group",
                            Photo = "https://angular.dev/assets/images/tutorials/common/r-architecture-JvQ0Q5IkeMM-unsplash.jpg",
                            State = "CA",
                            Wifi = true
                        },
                        new
                        {
                            Id = 7,
                            AvailableUnits = 5,
                            City = "Oakland",
                            Laundry = true,
                            Name = "Seriously Safe Towns",
                            Photo = "https://angular.dev/assets/images/tutorials/common/phil-hearing-IYfp2Ixe9nM-unsplash.jpg",
                            State = "CA",
                            Wifi = true
                        },
                        new
                        {
                            Id = 8,
                            AvailableUnits = 2,
                            City = "Oakland",
                            Laundry = true,
                            Name = "Hopeful Housing Solutions",
                            Photo = "https://angular.dev/assets/images/tutorials/common/r-architecture-GGupkreKwxA-unsplash.jpg",
                            State = "CA",
                            Wifi = true
                        },
                        new
                        {
                            Id = 9,
                            AvailableUnits = 10,
                            City = "Oakland",
                            Laundry = false,
                            Name = "Seriously Safe Towns",
                            Photo = "https://angular.dev/assets/images/tutorials/common/saru-robert-9rP3mxf8qWI-unsplash.jpg",
                            State = "CA",
                            Wifi = false
                        },
                        new
                        {
                            Id = 10,
                            AvailableUnits = 6,
                            City = "Portland",
                            Laundry = true,
                            Name = "Capital Safe Towns",
                            Photo = "https://angular.dev/assets/images/tutorials/common/webaliser-_TPTXZd9mOo-unsplash.jpg",
                            State = "OR",
                            Wifi = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
